### ISSUE TITLE
3.8.6最近几天运行一段时间会自动变成未运行

### ISSUE THREAD

**Issue by spirytuslove** [1wrt/luci-app-ikoolproxy#96]
3.8.6最近几天运行一段时间会自动变成未运行 而且变成未运行会导致刷网页都卡重新启动下又变成运行中  过段时间又会变成未运行。。。 op内核5.4

**Comment by Beginner-Go** [comment]
不是这边问题，应该linux内核更新导致的

**Comment by spirytuslove** [comment]
> 不是这边问题，应该linux内核更新导致的

我没有更新op啊 这样内核也会变吗

**Comment by 1wrt** [comment]
我自己路由是5.4，没有你所反应的问题。
